export const workersData =  [
    { id: 1, name: "Alice Smith", country: "United States", profileImage: "https://randomuser.me/api/portraits/lego/0.jpg", countryFlag: "https://flagcdn.com/w320/us.png", workerRole: "Astrologer" },
    { id: 2, name: "Bob Johnson", country: "Canada", profileImage: "https://randomuser.me/api/portraits/lego/1.jpg", countryFlag: "https://flagcdn.com/w320/ca.png", workerRole: "Mehndi" },
    { id: 3, name: "Charlie Brown", country: "Mexico", profileImage: "https://randomuser.me/api/portraits/lego/2.jpg", countryFlag: "https://flagcdn.com/w320/mx.png", workerRole: "Photographer" },
    { id: 4, name: "Diana Prince", country: "United Kingdom", profileImage: "https://randomuser.me/api/portraits/lego/3.jpg", countryFlag: "https://flagcdn.com/w320/gb.png", workerRole: "Assistant" },
    { id: 5, name: "Edward Green", country: "China", profileImage: "https://randomuser.me/api/portraits/lego/4.jpg", countryFlag: "https://flagcdn.com/w320/cn.png", workerRole: "Makeup" },
    { id: 6, name: "Fiona Harris", country: "Australia", profileImage: "https://randomuser.me/api/portraits/lego/5.jpg", countryFlag: "https://flagcdn.com/w320/au.png", workerRole: "Astrologer" },
    { id: 7, name: "George Wilson", country: "South Korea", profileImage: "https://randomuser.me/api/portraits/lego/6.jpg", countryFlag: "https://flagcdn.com/w320/kr.png", workerRole: "Mehndi" },
    { id: 8, name: "Hannah Lewis", country: "Brazil", profileImage: "https://randomuser.me/api/portraits/lego/7.jpg", countryFlag: "https://flagcdn.com/w320/br.png", workerRole: "Photographer" },
    { id: 9, name: "Isaac Young", country: "India", profileImage: "https://randomuser.me/api/portraits/lego/8.jpg", countryFlag: "https://flagcdn.com/w320/in.png", workerRole: "Assistant" },
    { id: 10, name: "Jessica Adams", country: "Germany", profileImage: "https://randomuser.me/api/portraits/lego/9.jpg", countryFlag: "https://flagcdn.com/w320/de.png", workerRole: "Makeup" },
    { id: 11, name: "Kevin Brown", country: "France", profileImage: "https://randomuser.me/api/portraits/lego/10.jpg", countryFlag: "https://flagcdn.com/w320/fr.png", workerRole: "Astrologer" },
    { id: 12, name: "Lily King", country: "Spain", profileImage: "https://randomuser.me/api/portraits/lego/11.jpg", countryFlag: "https://flagcdn.com/w320/es.png", workerRole: "Mehndi" },
    { id: 13, name: "Mason Scott", country: "Italy", profileImage: "https://randomuser.me/api/portraits/lego/12.jpg", countryFlag: "https://flagcdn.com/w320/it.png", workerRole: "Photographer" },
    { id: 14, name: "Nina Moore", country: "Japan", profileImage: "https://randomuser.me/api/portraits/lego/13.jpg", countryFlag: "https://flagcdn.com/w320/jp.png", workerRole: "Assistant" },
    { id: 15, name: "Oscar Turner", country: "South Africa", profileImage: "https://randomuser.me/api/portraits/lego/14.jpg", countryFlag: "https://flagcdn.com/w320/za.png", workerRole: "Makeup" },
    { id: 16, name: "Paula Lee", country: "Russia", profileImage: "https://randomuser.me/api/portraits/lego/15.jpg", countryFlag: "https://flagcdn.com/w320/ru.png", workerRole: "Astrologer" },
    { id: 17, name: "Quincy Harris", country: "Netherlands", profileImage: "https://randomuser.me/api/portraits/lego/16.jpg", countryFlag: "https://flagcdn.com/w320/nl.png", workerRole: "Mehndi" },
    { id: 18, name: "Rachel Walker", country: "Sweden", profileImage: "https://randomuser.me/api/portraits/lego/17.jpg", countryFlag: "https://flagcdn.com/w320/se.png", workerRole: "Photographer" },
    { id: 19, name: "Sam Evans", country: "Norway", profileImage: "https://randomuser.me/api/portraits/lego/18.jpg", countryFlag: "https://flagcdn.com/w320/no.png", workerRole: "Assistant" },
    { id: 20, name: "Tina Mitchell", country: "Denmark", profileImage: "https://randomuser.me/api/portraits/lego/19.jpg", countryFlag: "https://flagcdn.com/w320/dk.png", workerRole: "Makeup" },
    { id: 21, name: "Ulysses Carter", country: "Finland", profileImage: "https://randomuser.me/api/portraits/lego/20.jpg", countryFlag: "https://flagcdn.com/w320/fi.png", workerRole: "Astrologer" },
    { id: 22, name: "Vera Roberts", country: "Ireland", profileImage: "https://randomuser.me/api/portraits/lego/21.jpg", countryFlag: "https://flagcdn.com/w320/ie.png", workerRole: "Mehndi" },
    { id: 23, name: "William Scott", country: "Portugal", profileImage: "https://randomuser.me/api/portraits/lego/22.jpg", countryFlag: "https://flagcdn.com/w320/pt.png", workerRole: "Photographer" },
    { id: 24, name: "Xena Cooper", country: "Austria", profileImage: "https://randomuser.me/api/portraits/lego/23.jpg", countryFlag: "https://flagcdn.com/w320/at.png", workerRole: "Assistant" },
    { id: 25, name: "Yvonne Thompson", country: "Belgium", profileImage: "https://randomuser.me/api/portraits/lego/24.jpg", countryFlag: "https://flagcdn.com/w320/be.png", workerRole: "Makeup" },
    { id: 26, name: "Zachary Carter", country: "Switzerland", profileImage: "https://randomuser.me/api/portraits/lego/25.jpg", countryFlag: "https://flagcdn.com/w320/ch.png", workerRole: "Astrologer" },
    { id: 27, name: "Ava Johnson", country: "Singapore", profileImage: "https://randomuser.me/api/portraits/lego/26.jpg", countryFlag: "https://flagcdn.com/w320/sg.png", workerRole: "Mehndi" },
    { id: 28, name: "Benjamin Lee", country: "Malaysia", profileImage: "https://randomuser.me/api/portraits/lego/27.jpg", countryFlag: "https://flagcdn.com/w320/my.png", workerRole: "Photographer" },
    { id: 29, name: "Chloe Garcia", country: "Thailand", profileImage: "https://randomuser.me/api/portraits/lego/28.jpg", countryFlag: "https://flagcdn.com/w320/th.png", workerRole: "Assistant" },
    { id: 30, name: "Daniel Wilson", country: "Vietnam", profileImage: "https://randomuser.me/api/portraits/lego/29.jpg", countryFlag: "https://flagcdn.com/w320/vn.png", workerRole: "Makeup" },
    { id: 31, name: "Emily Martinez", country: "Philippines", profileImage: "https://randomuser.me/api/portraits/lego/30.jpg", countryFlag: "https://flagcdn.com/w320/ph.png", workerRole: "Astrologer" },
    { id: 32, name: "Frank Robinson", country: "New Zealand", profileImage: "https://randomuser.me/api/portraits/lego/31.jpg", countryFlag: "https://flagcdn.com/w320/nz.png", workerRole: "Mehndi" },
    { id: 33, name: "Grace Hernandez", country: "Pakistan", profileImage: "https://randomuser.me/api/portraits/lego/32.jpg", countryFlag: "https://flagcdn.com/w320/pk.png", workerRole: "Photographer" },
    { id: 34, name: "Henry Clark", country: "Sri Lanka", profileImage: "https://randomuser.me/api/portraits/lego/33.jpg", countryFlag: "https://flagcdn.com/w320/lk.png", workerRole: "Assistant" },
    { id: 35, name: "Isabella Adams", country: "Bangladesh", profileImage: "https://randomuser.me/api/portraits/lego/34.jpg", countryFlag: "https://flagcdn.com/w320/bd.png", workerRole: "Makeup" },
    { id: 36, name: "Jacob Evans", country: "Nepal", profileImage: "https://randomuser.me/api/portraits/lego/35.jpg", countryFlag: "https://flagcdn.com/w320/np.png", workerRole: "Astrologer" },
    { id: 37, name: "Kaitlyn Moore", country: "Myanmar", profileImage: "https://randomuser.me/api/portraits/lego/36.jpg", countryFlag: "https://flagcdn.com/w320/mm.png", workerRole: "Mehndi" },
    { id: 38, name: "Leo Grant", country: "Cambodia", profileImage: "https://randomuser.me/api/portraits/lego/37.jpg", countryFlag: "https://flagcdn.com/w320/kh.png", workerRole: "Photographer" },
    { id: 39, name: "Maya Patel", country: "Sri Lanka", profileImage: "https://randomuser.me/api/portraits/lego/38.jpg", countryFlag: "https://flagcdn.com/w320/lk.png", workerRole: "Assistant" },
    { id: 40, name: "Nico Romero", country: "Peru", profileImage: "https://randomuser.me/api/portraits/lego/39.jpg", countryFlag: "https://flagcdn.com/w320/pe.png", workerRole: "Makeup" },
    { id: 41, name: "Olivia Lewis", country: "Colombia", profileImage: "https://randomuser.me/api/portraits/lego/40.jpg", countryFlag: "https://flagcdn.com/w320/co.png", workerRole: "Astrologer" },
    { id: 42, name: "Paul Young", country: "Ecuador", profileImage: "https://randomuser.me/api/portraits/lego/41.jpg", countryFlag: "https://flagcdn.com/w320/ec.png", workerRole: "Mehndi" },
    { id: 43, name: "Quinn Morgan", country: "Bolivia", profileImage: "https://randomuser.me/api/portraits/lego/42.jpg", countryFlag: "https://flagcdn.com/w320/bo.png", workerRole: "Photographer" },
    { id: 44, name: "Riley Scott", country: "Paraguay", profileImage: "https://randomuser.me/api/portraits/lego/43.jpg", countryFlag: "https://flagcdn.com/w320/py.png", workerRole: "Assistant" },
];
